name: flutter_github_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  dio: ^5.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
